In [169]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn as sk
import seaborn as sns
import seaborn.objects as so

from formulaic import Formula 

from sklearn.metrics import mean_squared_error, r2_score, root_mean_squared_error

# Operaciones con dataframes, limpieza y transformación de datos.

Para éstos ejercicios, usar el dataset _penguins_. En la mayoría de los ejercicios se pide realizar varias transformaciones de un DataFrame. En éstos ejercicios, ver primero la forma de hacerlo "de cualquier manera", utilizando una o varias instrucciones. Luego, si es posible, hacerlo mediante una sola instrucción encadenando las operaciones.
En todos los ejercicios, cuando se pide alguna condición resolver el ejercicio implementando esa condición, no resolverlo a mano. Por ejemplo, si se pide una lista de nombres de columnas de 14 caracteres, podemos hacer

``` [col for col in penguins.columns if len(col)==14]```

### 1. A partir del dataset penguins, crear un subconjunto de datos que contenga sólo pingüinos de la isla Biscoe y que tengan un pico de 48 mm o más

In [170]:
import seaborn as sns
penguins = sns.load_dataset("penguins")
penguins.island.unique()

<StringArray>
['Torgersen', 'Biscoe', 'Dream']
Length: 3, dtype: str

In [171]:
pinguinosBiscoe48 = penguins[(penguins["island"]== "Biscoe") & (penguins["bill_length_mm"] >=48)]
pinguinosBiscoe48.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
221,Gentoo,Biscoe,50.0,16.3,230.0,5700.0,Male
222,Gentoo,Biscoe,48.7,14.1,210.0,4450.0,Female
223,Gentoo,Biscoe,50.0,15.2,218.0,5700.0,Male
231,Gentoo,Biscoe,49.0,16.1,216.0,5550.0,Male
233,Gentoo,Biscoe,48.4,14.6,213.0,5850.0,Male

### 2. Crear otro dataset con la información de pingüinos Adelie machos que no sean de la isla Biscoe

In [172]:
adelieMachosNotBiscoe = penguins[(penguins["species"]== "Adelie") & (penguins["sex"] == "Male")&(penguins["island"]!="Biscoe")]

adelieMachosNotBiscoe

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,Male
13,Adelie,Torgersen,38.6,21.2,191.0,3800.0,Male
14,Adelie,Torgersen,34.6,21.1,198.0,4400.0,Male
17,Adelie,Torgersen,42.5,20.7,197.0,4500.0,Male
19,Adelie,Torgersen,46.0,21.5,194.0,4200.0,Male
31,Adelie,Dream,37.2,18.1,178.0,3900.0,Male
33,Adelie,Dream,40.9,18.9,184.0,3900.0,Male
35,Adelie,Dream,39.2,21.1,196.0,4150.0,Male
36,Adelie,Dream,38.8,20.0,190.0,3950.0,Male
39,Adelie,Dream,39.8,19.1,184.0,4650.0,Male
41,Adelie,Dream,40.8,18.4,195.0,3900.0,Male
43,Adelie,Dream,44.1,19.7,196.0,4400.0,Male
45,Adelie,Dream,39.6,18.8,190.0,4600.0,Male
46,Adelie,Dream,41.1,19.0,182.0,3425.0,Male
49,Adelie,Dream,42.3,21.2,191.0,4150.0,Male
69,Adelie,Torgersen,41.8,19.4,198.0,4450.0,Male
71,Adelie,Torgersen,39.7,18.4,190.0,3900.0,Male
73,Adelie,Torgersen,45.8,18.9,197.0,4150.0,Male
75,Adelie,Torgersen,42.8,18.5,195.0,4250.0,Male
77,Adelie,Torgersen,37.2,19.4,184.0,3900.0,Male
79,Adelie,Torgersen,42.1,19.1,195.0,4000.0,Male
81,Adelie,Torgersen,42.9,17.6,196.0,4700.0,Male
83,Adelie,Torgersen,35.1,19.4,193.0,4200.0,Male
85,Adelie,Dream,41.3,20.3,194.0,3550.0,Male
86,Adelie,Dream,36.3,19.5,190.0,3800.0,Male
88,Adelie,Dream,38.3,19.2,189.0,3950.0,Male
91,Adelie,Dream,41.1,18.1,205.0,4300.0,Male
93,Adelie,Dream,39.6,18.1,186.0,4450.0,Male
95,Adelie,Dream,40.8,18.9,208.0,4300.0,Male
97,Adelie,Dream,40.3,18.5,196.0,4350.0,Male
99,Adelie,Dream,43.2,18.5,192.0,4100.0,Male
117,Adelie,Torgersen,37.3,20.5,199.0,3775.0,Male
119,Adelie,Torgersen,41.1,18.6,189.0,3325.0,Male
121,Adelie,Torgersen,37.7,19.8,198.0,3500.0,Male
123,Adelie,Torgersen,41.4,18.5,202.0,3875.0,Male
125,Adelie,Torgersen,40.6,19.0,199.0,4000.0,Male
127,Adelie,Torgersen,41.5,18.3,195.0,4300.0,Male
129,Adelie,Torgersen,44.1,18.0,210.0,4000.0,Male
131,Adelie,Torgersen,43.1,19.2,197.0,3500.0,Male
133,Adelie,Dream,37.5,18.5,199.0,4475.0,Male
135,Adelie,Dream,41.1,17.5,190.0,3900.0,Male
137,Adelie,Dream,40.2,20.1,200.0,3975.0,Male
139,Adelie,Dream,39.7,17.9,193.0,4250.0,Male
141,Adelie,Dream,40.6,17.2,187.0,3475.0,Male
143,Adelie,Dream,40.7,17.0,190.0,3725.0,Male
145,Adelie,Dream,39.0,18.7,185.0,3650.0,Male
146,Adelie,Dream,39.2,18.6,190.0,4250.0,Male
149,Adelie,Dream,37.8,18.1,193.0,3750.0,Male
151,Adelie,Dream,41.5,18.5,201.0,4000.0,Male

### 3. Del dataset _penguins_ quedarse con todas las variables excepto year, sex y body_mass_g
Sugerencia: utilizar el método drop() de DataFrames

In [173]:
penguinsNew = penguins.drop(columns=['sex','body_mass_g']) #El dataframe no tiene columna sex
penguinsNew

    species     island  bill_length_mm  bill_depth_mm  flipper_length_mm
0    Adelie  Torgersen            39.1           18.7              181.0
1    Adelie  Torgersen            39.5           17.4              186.0
2    Adelie  Torgersen            40.3           18.0              195.0
3    Adelie  Torgersen             NaN            NaN                NaN
4    Adelie  Torgersen            36.7           19.3              193.0
..      ...        ...             ...            ...                ...
339  Gentoo     Biscoe             NaN            NaN                NaN
340  Gentoo     Biscoe            46.8           14.3              215.0
341  Gentoo     Biscoe            50.4           15.7              222.0
342  Gentoo     Biscoe            45.2           14.8              212.0
343  Gentoo     Biscoe            49.9           16.1              213.0

[344 rows x 5 columns]

In [174]:
# Otra forma de hacerlo

penguinsNew2 = penguins[[col for col in penguins.columns if not(col in ['year','sex','body_mass_g'])]]
penguinsNew2

    species     island  bill_length_mm  bill_depth_mm  flipper_length_mm
0    Adelie  Torgersen            39.1           18.7              181.0
1    Adelie  Torgersen            39.5           17.4              186.0
2    Adelie  Torgersen            40.3           18.0              195.0
3    Adelie  Torgersen             NaN            NaN                NaN
4    Adelie  Torgersen            36.7           19.3              193.0
..      ...        ...             ...            ...                ...
339  Gentoo     Biscoe             NaN            NaN                NaN
340  Gentoo     Biscoe            46.8           14.3              215.0
341  Gentoo     Biscoe            50.4           15.7              222.0
342  Gentoo     Biscoe            45.2           14.8              212.0
343  Gentoo     Biscoe            49.9           16.1              213.0

[344 rows x 5 columns]

### 4. Empezando con _penguins_ escribir una secuencia de operaciones que :

(a) Excluya a los pingüinos observados en la isla Biscoe.

(b) Sólo se quede con las variables que están entre _species_ y *body_mass_g* inclusive.

(c) Renombre la variable _species_ a *especie_pinguino*

(d) Agrupe los datos por la variable *especie_pinguino*

(e) Calcule el valor medio de las variables que contienen el valor "length", separado por la especie del pingüino, y llamando a las columnas como las originales pero agregando el "_mean" al final.

In [175]:
# (a)
penguinsNotBiscoe = penguins[penguins["island"]!="Biscoe"]
# (b)
penguinsNotBiscoe = penguinsNotBiscoe[[col for col in penguins.columns if not(col in ['sex'])]]
# (c)
penguinsNotBiscoe.rename(columns= {"species":"especie_pinguino"},inplace = True)


# (d)

penguinsNotBiscoe.groupby("especie_pinguino")

# (e)

penguinsNotBiscoe.groupby("especie_pinguino").agg({col: "mean" for col in penguinsNotBiscoe.columns if "length" in col}).rename(columns={"bill_length_mm":"bill_length_mm_mean","flipper_length_mm":"flipper_length_mm_mean"})

                  bill_length_mm_mean  flipper_length_mm_mean
especie_pinguino
Adelie                      38.715888              190.429907
Chinstrap                   48.833824              195.823529

### Renombrar columnas e índices

Para renombrar columnas utilizamos .rename(columns = ???)
y para renombrar índices utilizamos .rename(index = ???)

Realizar las siguientes operaciones en el dataset _penguins_

(a) Renombrar la variable species a especies. En éste caso debemos pasarle a _columns_ un diccionario : {'variable_original':'variable_nueva'}

In [176]:
ejercicio5 = penguins.rename(columns={"species":"especie"})
ejercicio5

,especie,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

(b) Renombrar en un solo rename la variable flipper_length_mm a aleta_mm y la variable body_mass_g a peso_g

In [177]:
ejercicio5.rename(columns={"flipper_length_mm":"aleta_mm","body_mass_g":"peso_g"},inplace =True)
ejercicio5

,especie,island,bill_length_mm,bill_depth_mm,aleta_mm,peso_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

(c) Renombrar el índice 0 a "cero".

In [178]:
ejercicio5.rename(index={0:'cero'},inplace= True)
ejercicio5

,especie,island,bill_length_mm,bill_depth_mm,aleta_mm,peso_g,sex
cero,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

(d) Pasar todos los nombres de variables a mayúsculas. Sugerencia : en lugar de un diccionario, podemos pasarle a columns una función. En éste caso, podemos usar la función str.upper

In [179]:
ejercicio5.rename(columns=  str.upper)

,ESPECIE,ISLAND,BILL_LENGTH_MM,BILL_DEPTH_MM,ALETA_MM,PESO_G,SEX
cero,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

¿Qué resultado esperan del siguiente comando?
penguins.rename(index = np.sqrt)

Yo espero que le aplique raíz cuadrada a todos los elementos (no va a funcionar sobre ejercicio5 porque cambiamos el 0 por un "cero")

In [180]:
#penguins.rename(index = np.sqrt)

¿Cómo podemos sumarle uno a todos los índices de _penguins_? Sugerencia: definir primero una función suma_uno y utilizar ésta función al hacer rename.

Antes que nada voy a deshacer el rename que le hicimos la índice 0

In [181]:
ejercicio5.rename(index={'cero':0},inplace= True)
ejercicio5

def suma_uno(n):
    return n+1
ejercicio5.rename(index = suma_uno)

,especie,island,bill_length_mm,bill_depth_mm,aleta_mm,peso_g,sex
1,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
2,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
3,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
4,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
5,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
340,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
341,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
342,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
343,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
344,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

En python, al igual que en muchos lenguajes, podemos usar _funciones lambda_ , que nos permite crear funciones "al vuelo". ¿Qué resultado esperan del siguiente comando?

penguins.rename (index = lambda x: x*2)

Yo espero que multiplique por 2 todos los índices

In [182]:
ejercicio5.rename(index=lambda x: x * 2, inplace = True)
ejercicio5

,especie,island,bill_length_mm,bill_depth_mm,aleta_mm,peso_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
2,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
4,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
6,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
8,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
678,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
680,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
682,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
684,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
686,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

(h) ¿Cómo podemos usar una función lambda para renombrar todos los nombres de columnas a mayúsculas?

In [183]:
ejercicio5.rename(columns= lambda x : x.upper()).reset_index()

,index,ESPECIE,ISLAND,BILL_LENGTH_MM,BILL_DEPTH_MM,ALETA_MM,PESO_G,SEX
0,0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,2,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,4,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,6,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,8,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...,...
339,678,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,680,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,682,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,684,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,686,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

### 6. Datos faltantes
En el siguiente ejercicio, utilizamos el dataset *macro_full_columns.csv*

In [184]:
macro_full_columns = pd.read_csv('datasets/macro_full_columns.csv')
macro_full_columns.head()

,Unnamed: 0,Anio,FBKF.Construcciones.Priv_Publ,FBKF.Equi_Dur_Prod.Mat_Transp.Nac,FBKF.Equi_Dur_Prod.Mat_Transp.Import,FBKF.Equi_Dur_Prod.Maqui_YEqui.Nac,FBKF.Equi_Dur_Prod.Maqui_YEqui.Import,Consumo.Hogares,Consumo.Gobierno,Exportaciones,...,PBI_a_precios_de_mercado.oferta,Vol_PIB_perCap,Vol_Consumo_Hogares_Per_Cap,Vol_FBKF_perCap,PIB_perCap__variPorc,Vol_Cons_Hogares_per_Cap__vari_Porc,Vol_FBKF_perCap__variPorc,Vol_PIB_encaden_Fisher_2004,IPI_volumen,IPI__variPorc
0,1,1950,20353627362,6.685869e+08,5.844002e+08,3119383475,8.631124e+08,1.046560e+11,21706316451,1.072959e+10,...,1.420980e+11,8230.718755,6061.927168,1265.389774,NaN,NaN,NaN,1.420980e+11,0.292917,NaN
1,2,1951,21739314091,8.427402e+08,2.532758e+09,3562534310,1.292775e+09,1.105380e+11,21767097618,8.455494e+09,...,1.474360e+11,8360.967138,6268.494407,1442.153759,0.015825,0.034076,0.139691,1.474360e+11,0.303920,0.037563
2,3,1952,19685428171,1.119084e+09,1.484422e+09,3440750327,1.088416e+09,1.051080e+11,21455589059,6.224082e+09,...,1.404910e+11,7806.866125,5840.680245,1293.154332,-0.066272,-0.068248,-0.103317,1.404910e+11,0.289604,-0.047104
3,4,1953,20237375978,1.207891e+09,1.459989e+09,3621895632,8.869267e+08,1.064030e+11,20742065172,9.619869e+09,...,1.473240e+11,8027.665603,5797.868309,1290.488829,0.028283,-0.007330,-0.002061,1.473240e+11,0.303689,0.048637
4,5,1954,19372130307,1.173452e+09,8.059002e+08,4121320340,7.830799e+08,1.143920e+11,21238933697,1.020162e+10,...,1.533160e+11,8196.878491,6115.886428,1230.475866,0.021079,0.054851,-0.046504,1.533160e+11,0.316039,0.040667

¿En qué columnas hay datos faltantes? Podemos usar df.isna().sum(axis = ???) o df.isna().any(axis=???). ¿Cuál es la diferencia? ¿Cómo podemos generar una lista que tenga solamente los nombres de las columnas con datos faltantes?

In [185]:
macro_full_columns.isna().sum()

Unnamed: 0                              0
Anio                                    0
FBKF.Construcciones.Priv_Publ           0
FBKF.Equi_Dur_Prod.Mat_Transp.Nac       0
FBKF.Equi_Dur_Prod.Mat_Transp.Import    0
                                       ..
Vol_Cons_Hogares_per_Cap__vari_Porc     1
Vol_FBKF_perCap__variPorc               1
Vol_PIB_encaden_Fisher_2004             0
IPI_volumen                             0
IPI__variPorc                           1
Length: 85, dtype: int64

In [186]:
macro_full_columns.isna().any()

Unnamed: 0                              False
Anio                                    False
FBKF.Construcciones.Priv_Publ           False
FBKF.Equi_Dur_Prod.Mat_Transp.Nac       False
FBKF.Equi_Dur_Prod.Mat_Transp.Import    False
                                        ...
Vol_Cons_Hogares_per_Cap__vari_Porc      True
Vol_FBKF_perCap__variPorc                True
Vol_PIB_encaden_Fisher_2004             False
IPI_volumen                             False
IPI__variPorc                            True
Length: 85, dtype: bool

In [187]:
columnas_nan = macro_full_columns.columns[macro_full_columns.isna().any()].tolist()
columnas_nan

['EXPO_OTAGRIC_2004',
 'EXPO_PESCA_2004',
 'EXPO_ALIMENT_2004',
 'EXPO_TEXTIL_2004',
 'EXPO_CUEROIND_2004',
 'EXPO_PAPEL_2004',
 'EXPO_CAUCHO_2004',
 'EXPO_QUIMICO_2004',
 'EXPO_COMBIUST_2004',
 'EXPO_HIERRO_2004',
 'EXPO_METNOFERR_2004',
 'EXPO_MAQUIN_2004',
 'EXPO_RESTOIND_2004',
 'PIB_perCap__variPorc',
 'Vol_Cons_Hogares_per_Cap__vari_Porc',
 'Vol_FBKF_perCap__variPorc',
 'IPI__variPorc']

¿En qué años hay datos faltantes? Listar todos los años con datos faltantes.

In [188]:
aniosNan = macro_full_columns[macro_full_columns.isna().any(axis =1)]

aniosNan['Anio'].tolist()

[1950,
 1951,
 1952,
 1953,
 1954,
 1955,
 1956,
 1957,
 1958,
 1959,
 1960,
 1961,
 1962,
 1963,
 1964,
 1965]

Convertir todos los datos faltantes a 0.

In [189]:
macro_full_columns.fillna(0,inplace=True)
macro_full_columns

,Unnamed: 0,Anio,FBKF.Construcciones.Priv_Publ,FBKF.Equi_Dur_Prod.Mat_Transp.Nac,FBKF.Equi_Dur_Prod.Mat_Transp.Import,FBKF.Equi_Dur_Prod.Maqui_YEqui.Nac,FBKF.Equi_Dur_Prod.Maqui_YEqui.Import,Consumo.Hogares,Consumo.Gobierno,Exportaciones,...,PBI_a_precios_de_mercado.oferta,Vol_PIB_perCap,Vol_Consumo_Hogares_Per_Cap,Vol_FBKF_perCap,PIB_perCap__variPorc,Vol_Cons_Hogares_per_Cap__vari_Porc,Vol_FBKF_perCap__variPorc,Vol_PIB_encaden_Fisher_2004,IPI_volumen,IPI__variPorc
0,1,1950,20353627362,6.685869e+08,5.844002e+08,3119383475,8.631124e+08,1.046560e+11,21706316451,1.072959e+10,...,1.420980e+11,8230.718755,6061.927168,1265.389774,0.000000,0.000000,0.000000,1.420980e+11,0.292917,0.000000
1,2,1951,21739314091,8.427402e+08,2.532758e+09,3562534310,1.292775e+09,1.105380e+11,21767097618,8.455494e+09,...,1.474360e+11,8360.967138,6268.494407,1442.153759,0.015825,0.034076,0.139691,1.474360e+11,0.303920,0.037563
2,3,1952,19685428171,1.119084e+09,1.484422e+09,3440750327,1.088416e+09,1.051080e+11,21455589059,6.224082e+09,...,1.404910e+11,7806.866125,5840.680245,1293.154332,-0.066272,-0.068248,-0.103317,1.404910e+11,0.289604,-0.047104
3,4,1953,20237375978,1.207891e+09,1.459989e+09,3621895632,8.869267e+08,1.064030e+11,20742065172,9.619869e+09,...,1.473240e+11,8027.665603,5797.868309,1290.488829,0.028283,-0.007330,-0.002061,1.473240e+11,0.303689,0.048637
4,5,1954,19372130307,1.173452e+09,8.059002e+08,4121320340,7.830799e+08,1.143920e+11,21238933697,1.020162e+10,...,1.533160e+11,8196.878491,6115.886428,1230.475866,0.021079,0.054851,-0.046504,1.533160e+11,0.316039,0.040667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,62,2011,66813943052,1.189902e+10,7.661349e+09,23759578339,4.132673e+10,5.014680e+11,80184420870,1.598420e+11,...,7.118760e+11,17252.803350,12153.418950,3506.313415,0.048057,0.072793,0.138625,7.118760e+11,1.467438,0.060211
62,63,2012,64700327691,1.193748e+10,5.518154e+09,21650676546,3.568329e+10,4.998770e+11,82549920556,1.531870e+11,...,7.064210e+11,16927.042940,11977.906860,3255.742019,-0.018882,-0.014441,-0.071463,7.064210e+11,1.456192,-0.007664
63,64,2013,64634666531,1.378317e+10,7.239125e+09,24156151830,3.373643e+10,5.165960e+11,86152836238,1.464500e+11,...,7.220400e+11,17108.767060,12240.750480,3317.537236,0.010736,0.021944,0.018980,7.220400e+11,1.488389,0.022110
64,65,2014,63301703123,1.030574e+10,5.950583e+09,21378949359,3.253840e+10,4.967300e+11,89033326375,1.367560e+11,...,7.056120e+11,16536.677200,11641.346310,3071.164706,-0.033438,-0.048968,-0.074264,7.056120e+11,1.454524,-0.022753
65,66,2015,64462175043,1.143976e+10,5.599293e+09,24228907045,3.441289e+10,5.098710e+11,94456349868,1.355150e+11,...,7.225620e+11,16752.344150,11821.179420,3176.115695,0.013042,0.015448,0.034173,7.225620e+11,1.489464,0.024021

### 7 Reestablecer índices
(a) en el dataset _penguins_ , eliminar primero todas las filas con datos faltantes. ¿Qué sucede con los índices?

In [190]:
penguinsSinNaN = penguins.dropna()
penguinsSinNaN

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male
...,...,...,...,...,...,...,...
338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,Female
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

(b) En el dataset sin datos faltantes, reestablecer los índices mediante el comando reset_index()

In [191]:
penguinsSinNaN.reset_index()

,index,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
4,5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male
...,...,...,...,...,...,...,...,...
328,338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,Female
329,340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
330,341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
331,342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
332,343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

(c) ¿Cómo podemos hacer todo en un sólo comando encadenando operaciones?

In [198]:
penguinsClear = penguins.dropna().reset_index().drop(columns= 'index')
penguinsClear

,species,island,BILL_LENGTH_MM,BILL_DEPTH_MM,flipper_length_mm,body_mass_g,sex,peso_bin
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,chico
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,chico
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,chico
3,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,chico
4,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male,chico
...,...,...,...,...,...,...,...,...
328,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,Female,grande
329,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female,grande
330,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male,grande
331,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female,grande
332,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male,grande

### 8 df.columns.
También podemos renombrar columnas asignando una nueva lista de nombres mediante *penguins.columns = ???* . En éste caso, resulta útil definir _listas por comprensión_

La sintaxis es [f(x) for x in LIST]

(a)¿Qué resultado esperan de ejecutar éste comando?
[saludo + '!' for saludo in ['hola',chau']]

Debería decir
Hola!,
Chau!

In [199]:
[saludo + '!' for saludo in ['hola','chau']]

['hola!', 'chau!']

(b) En el dataset _penguins_, convertir todos los nombres de variables a mayúsculas utilizando listas por comprensión.

In [200]:
penguinsAux = penguins.copy()
penguinsAux.columns = [col.upper() for col in penguinsAux.columns ]
penguinsAux

,SPECIES,ISLAND,BILL_LENGTH_MM,BILL_DEPTH_MM,FLIPPER_LENGTH_MM,BODY_MASS_G,SEX,PESO_BIN
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,chico
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,chico
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,chico
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,grande
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,chico
...,...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,grande
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female,grande
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male,grande
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female,grande
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male,grande

### 9 En el dataset _penguins_ convertir sólo los nombres de variables que empiezan con bill a mayúsculas

In [201]:
penguins.columns = [col.upper() if col.startswith('bill') else col for col in penguins.columns]
penguins

,species,island,BILL_LENGTH_MM,BILL_DEPTH_MM,flipper_length_mm,body_mass_g,sex,peso_bin
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,chico
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,chico
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,chico
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,grande
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,chico
...,...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,grande
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female,grande
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male,grande
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female,grande
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male,grande

### Ejercicio 10 
Utilizando una función lambda, agregar una nueva columna a la base de datos llamada peso_bin que contenga :
- "chico" si la masa corporal es menos que 4000 gramos
- "grande" si la masa corporal es mayor que 4000 gramos

In [203]:
separar = lambda x : "chico" if x < 4000 else "grande"

penguinsClear['peso_bin'] = penguinsClear['body_mass_g'].apply(separar)

penguinsClear

,species,island,BILL_LENGTH_MM,BILL_DEPTH_MM,flipper_length_mm,body_mass_g,sex,peso_bin
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,chico
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,chico
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,chico
3,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,chico
4,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male,chico
...,...,...,...,...,...,...,...,...
328,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,Female,grande
329,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female,grande
330,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male,grande
331,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female,grande
332,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male,grande