# Estadistica descriptiva
### Estructuras de datos en Pandas

**Series** . Las series de Pandas son vectores similares a los arrays de NumPy, que podemos indexar usando etiquetas.

## Ejercicio 1
Crear la siguiente Series, observar que devuelve array e index e interpretar

In [1]:
import numpy as np
import pandas as pd
obj = pd.Series([7,4,-5,3])
display(obj)
display(obj.array)
display(obj.index) # Por default los indices van de 0 a n-1.

0    7
1    4
2   -5
3    3
dtype: int64

<NumpyExtensionArray>
[7, 4, -5, 3]
Length: 4, dtype: int64

RangeIndex(start=0, stop=4, step=1)

## Ejercicio 2
Podemos asignar etiquetas (o índices) a cada valor de la serie.

In [2]:
obj2 = pd.Series([np.pi,0,-2,1.41], index=['d','b','c','a'])
display(obj2)
display(obj2.array)
display(obj2.index)

d    3.141593
b    0.000000
c   -2.000000
a    1.410000
dtype: float64

<NumpyExtensionArray>
[3.141592653589793, 0.0, -2.0, 1.41]
Length: 4, dtype: float64

Index(['d', 'b', 'c', 'a'], dtype='str')

## Ejercicio 3
Al igual que con arrays de Numpy podemos acceder a los elementos por su posición , o podemos usar las etiquetas. Ejecutar los siguientes comandos:

In [3]:
print(obj2["a"])
# obj2[3] ésto no funca, ya que cambiamos las etiquetas
print(obj2[1:3])

obj3 = obj2 [["a","b"]]
print(obj3)
print(obj3.index)

print(obj2[obj2>1])

1.41
b    0.0
c   -2.0
dtype: float64
a    1.41
b    0.00
dtype: float64
Index(['a', 'b'], dtype='str')
d    3.141593
a    1.410000
dtype: float64

## Ejercicio 4
Las operaciones que pueden aplicarse a numpy arrays pueden aplicarse también a series de Pandas, conservando los índices.

In [4]:
np.exp(obj2)
obj2 * 3

d    9.424778
b    0.000000
c   -6.000000
a    4.230000
dtype: float64

## Ejercicio 5
### Métodos de series
Ejecutar los siguientes comandos e interpretar qué hace cada uno.

In [5]:
series1 = pd.Series(["a","b","c","b","a","c","c","x"])

In [6]:
series1.isin(["b","c"])

0    False
1     True
2     True
3     True
4    False
5     True
6     True
7    False
dtype: bool

In [7]:
series1.value_counts()

c    3
a    2
b    2
x    1
Name: count, dtype: int64

### DataFrames
Un DataFrame es una representación de los datos en formato de tabla donde las columnas son vectores del mismo tamaño. Como cada columna es un vector, cada columna puede contener datos de un único tipo. Se pueden pensar como variables. Cada variable corresponde a una serie de Pandas, y todas las series de un mismo DataFrame están indexadas por los mismos índices.

## Ejercicio 6 
Una forma de crear un DataFrame es utilizando un "diccionario". Todas las variables del diccionario deben ser vectores o listas de la misma longitud. Ejecutar el siguiente código.

In [8]:
data = {"nombre": ["Rodrigo", "Sergio", "Cristina", "Diana"] , "altura":
np . array ([178 , 172 , 175 , 168]) , "peso": np . array ([81.2 , 76.1 , 68.5 ,
64.0]) }
display ( data )

{'nombre': ['Rodrigo', 'Sergio', 'Cristina', 'Diana'],
 'altura': array([178, 172, 175, 168]),
 'peso': array([81.2, 76.1, 68.5, 64. ])}

In [9]:
pacientes = pd . DataFrame ( data ) . set_index ("nombre")
display ( pacientes )

          altura  peso
nombre
Rodrigo      178  81.2
Sergio       172  76.1
Cristina     175  68.5
Diana        168  64.0

## Ejercicio 7
¿ Cuál es la clase del objeto pacientes? ¿Cual es la clase de cada uno de los vectores columna? (Para saber la clase de un objeto, utilizar el comando _type_ , para saber el tipo de datos de un array de numpy , utilizar np.dtype)

In [10]:
type(pacientes)

pandas.DataFrame

In [11]:
np.dtype(pacientes["altura"])
np.dtype(pacientes["peso"])
# np.dtype(pacientes["nombre"]) . ¿Por qué no funciona ésto? Porque nombre no es una columna

dtype('float64')

## Ejercicio 8
Guardar en una variable nueva el vector columna altura. Pueden utilizar pacientes["altura"] o pacientes.altura(Es preferible la primera para evitar errores en caso de que en la segunda el nombre coincida con alguna función ya existente)

In [12]:
altura = pacientes["altura"]
altura

nombre
Rodrigo     178
Sergio      172
Cristina    175
Diana       168
Name: altura, dtype: int64

## Ejercicio 9
A diferencia de las matrices en Numpy, un DataFrame de Pandas es un **Conjunto de columnas** , no de filas. Pensar cuál de los dos comandos será correcto antes de ejecutarlos.

In [13]:
#pacientes["Rodrigo"].altura
pacientes["altura"].Rodrigo

np.int64(178)

Wtf en serio es la segunda la que funciona?

Claro, porque de la columna "altura" agarra el índice Rodrigo. Recontra remil anti intuitivo

### loc e iloc
Para evitar confusones , un DataFrame tiene atributos _loc_ e _iloc_ para indexar por etiquetas o por índice respectivamente. 
Dado que un DataFrame tiene dos dimensiones, se puede seleccionar un subset de las filas y las columnas con notación numpy usando tanto las etiquetas de los ejes, o los enteros.

In [14]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                     index=["Ohio", "Colorado", "Utah", "New York"],
                     columns=["one", "two", "three", "four"])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [15]:
data.loc["Colorado"]

one      4
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [16]:
data.loc[["Colorado","New York"]]

          one  two  three  four
Colorado    4    5      6     7
New York   12   13     14    15

In [17]:
data.iloc[1]

one      4
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [18]:
data.loc["Colorado"].iloc[2] #De la fila "Colorado" le pido la columna del índice 2 (osea la tercera)

np.int64(6)

Así sí es intuitivo. Para mí por lo menos.

In [19]:
data.loc[["Colorado","Utah"]].iloc[1,[1,2]]

two       9
three    10
Name: Utah, dtype: int64