In [1]:
import seaborn as sns
from sklearn.model_selection import KFold
import matplotlib.pyplot as plt

from scipy import stats
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from formulaic import model_matrix

In [2]:
#import os
#print(pwd)
#os.chdir('./notebooks')

# Limpieza de Datos

En Python, las funciones y paquetes para trabajar con datos no están pensadas para poder hacerlas "sin saber nada de Python". Al contrario, muchas operaciones sencillas de DataFrames requieren conocer técnicas de programación en Python. Vamos a ver algunas en esta clase, principalmente estas cuatro:

## 1. Diccionarios
## 2. Encadenamiento de métodos
## 3. Funciones lambda
## 4. Definición de listas por comprensión

**Ejercicio 1.** En el dataset de vinos de la última clase, renombrar la columna "od280/od315_of_diluted_wines" a "od280_od315_of_diluted_wines".

In [4]:
from sklearn.datasets import load_wine
wine = load_wine(as_frame=True)
wineData = wine.data
wineData.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0

Hay esencialmente dos formas de renombrar columnas:
1. Utilizar `rename()`
2. Modificar la lista de nombres de columnas `dataframe.columns`

Comenzamos con `rename()`.

In [6]:
pd.DataFrame.rename(wineData,columns={"od280/od315_of_diluted_wines":"od280_od315_of_diluted_wines"})

# O help(pd.DataFrame.rename)
# O wineData.rename??

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280_od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0

Vemos que podemos renombrar columnas utilizando `columns: dict-like or function`

## 1. Diccionarios
Los diccionarios se utilizan para almacenar valores de datos en pares clave:valor.

Un diccionario es una colección ordenada, modificable y que no permite duplicados.

In [7]:
# Ejemplo
dict = { "hola" : "Expresión de saludo utilizada entre dos o más personas de trato familiar", "cinco" : 5, "dias" : ["lunes", "martes", "miercoles"]}

In [8]:
dict["cinco"]

5

In [9]:
# Ejemplo
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict["brand"])

Ford

Para renombrar una columna, usamos rename(columns = _DICT_) y un diccionario con "nombre viejo" como claves y "nombre nuevo" como valores.

In [12]:
wineData.rename(columns = {"od280/od315_of_diluted_wines" : "od280_od315_of_diluted_wines"})  # No es necesario renombrar todas las columnas, podemos renombrar las que querramos.

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280_od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0

In [13]:
# Cambió algo?
wineData

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0

In [14]:
# Podemos guardar los cambios en el mismo DataFrame o en uno nuevo
wineClean = wineData.rename(columns = {"od280/od315_of_diluted_wines" : "od280_od315_of_diluted_wines"})
wineClean.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280_od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0

**Nota:** también existe la opción "inplace = True" pero no está recomendada (por ejemplo, no permite encadenar comandos).

### `rename` con funciones

También podemos usar funciones para renombrar columnas (Python permite pasar funciones como parámetros).

**Ejemplo:** Pasar todos los nombres de columnas a mayúsculas.

In [15]:
# Para pasar un string a mayusculas utilizamo str.upper
str.upper("hola")

'HOLA'

¿Cómo lo usarian para renombrar nuestras variables?

In [19]:
# Así?
wineData.rename(columns = str.upper)
# o así?
#wineData.rename(columns = str.upper())

,ALCOHOL,MALIC_ACID,ASH,ALCALINITY_OF_ASH,MAGNESIUM,TOTAL_PHENOLS,FLAVANOIDS,NONFLAVANOID_PHENOLS,PROANTHOCYANINS,COLOR_INTENSITY,HUE,OD280/OD315_OF_DILUTED_WINES,PROLINE
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0

<details>
<summary>Click para ver la respuesta</summary>

Le pasamos el nombre de la función, por eso va sin los paréntesis. 

Si la pasamos con paréntesis le estaríamos pasando el resultado de evaluar la función sin parámetros.
</details>

### Ejercicio

Definiendo tu propia función, agregar en todos los nombres de columna "_2026" al final del nombre.

In [26]:
def agregar2026 (data):
    return data.rename(columns= lambda x : x + "_2026")
agregar2026(wineData)

,alcohol_2026,malic_acid_2026,ash_2026,alcalinity_of_ash_2026,magnesium_2026,total_phenols_2026,flavanoids_2026,nonflavanoid_phenols_2026,proanthocyanins_2026,color_intensity_2026,hue_2026,od280/od315_of_diluted_wines_2026,proline_2026
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0

## 2. Encadenar métodos

### 2.a Datos faltantes

**Ejercicio 2.** En la base de dato de pingüinos, eliminar las filas con datos faltantes, y renumerar los índices comenzando en 1.

In [28]:
penguins = sns.load_dataset("penguins")
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

In [48]:
penguins_limpia = penguins.dropna()
penguins_limpia.index = range(1, len(penguins_limpia)+1)

penguins_limpia

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
1,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
2,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
3,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male
...,...,...,...,...,...,...,...
329,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,Female
330,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
331,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
332,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
333,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

## Primero: ¿qué son los datos faltantes?

¿Qué significa un valor faltante? Es un dato que por distintos motivos no fue ingresado (por ejemplo si juntamos datos de distintas fuentes, en alguna de las fuentes esa información puede no estar disponible).

Los datos faltantes son algo típico de cualquier pipeline de análisis de datos. En general los paquetes estadísticos (pandas, dplyr, etc) tratan de facilitar el manejo de estos tipos de datos. En Pandas, se utiliza la expresión NaN (Not a number) o NA que viene del mundo R (Not available)

In [49]:
# Vamos a trabajar con una base de eficiencia del sueño
datos = pd.read_csv("Sleep_efficiency_cleaning.csv")
datos

,ID,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Smoking status,Exercise frequency
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,0.0,0.0,Yes,3.0
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,0.0,3.0,Yes,3.0
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,1.0,0.0,0.0,No,3.0
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,3.0,50.0,5.0,Yes,1.0
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,0.0,3.0,No,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,197,30,Female,2021-08-05 00:00:00,2021-08-05 08:00:00,8.0,0.94,22,63,15,1.0,75.0,0.0,Yes,2.0
458,291,54,Male,2021-01-20 22:30:00,2021-01-20 06:30:00,8.0,0.84,18,60,22,3.0,0.0,0.0,No,3.0
459,102,53,Male,2021-01-28 01:00:00,2021-01-28 09:30:00,8.5,0.71,20,67,13,4.0,0.0,1.0,No,3.0
460,399,30,Female,2021-07-21 01:00:00,2021-07-21 08:00:00,7.0,0.91,28,52,20,0.0,50.0,0.0,No,0.0
461,31,24,Male,2021-08-10 00:00:00,2021-08-10 07:00:00,7.0,0.57,27,20,53,3.0,0.0,1.0,Yes,3.0

Para poder acceder a los datos faltantes, podemos utilizar la función `isna()`

¿Cómo la usamos? ¿Qué nos devuelve?

In [50]:
datos.isna()

,ID,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Smoking status,Exercise frequency
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
458,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
459,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
460,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
461,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

¿Cómo podemos transformar toda esta información para que sea más legible?

In [51]:
# Una forma bien simple sería usando 
datos.isna().sum()

ID                         0
Age                        0
Gender                     0
Bedtime                    0
Wakeup time                0
Sleep duration             0
Sleep efficiency           0
REM sleep percentage       0
Deep sleep percentage      0
Light sleep percentage     0
Awakenings                20
Caffeine consumption      25
Alcohol consumption       15
Smoking status             0
Exercise frequency         6
dtype: int64

In [52]:
# De ahi sabemos que Despertares, Consumo de cafeina, Consumo de alcohol y Frecuencia de ejercicio tienen datos faltantes

In [53]:
# Esto nos da lo mismo (null es comun en SQL, NaN se usa en NumPy)
penguins.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

¿Qué podríamos hacer con todos estos datos faltantes?

In [54]:
# Una posibilidad es usar dropna() 
# ¿Qué les parece que hace esta función? 
# ¿Cuántas filas teniamos antes y cuántas tenemos ahora? ¿Cuáles son las ventajas y desventajas de esto?

datos.dropna()

,ID,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Smoking status,Exercise frequency
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,0.0,0.0,Yes,3.0
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,0.0,3.0,Yes,3.0
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,1.0,0.0,0.0,No,3.0
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,3.0,50.0,5.0,Yes,1.0
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,0.0,3.0,No,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,197,30,Female,2021-08-05 00:00:00,2021-08-05 08:00:00,8.0,0.94,22,63,15,1.0,75.0,0.0,Yes,2.0
458,291,54,Male,2021-01-20 22:30:00,2021-01-20 06:30:00,8.0,0.84,18,60,22,3.0,0.0,0.0,No,3.0
459,102,53,Male,2021-01-28 01:00:00,2021-01-28 09:30:00,8.5,0.71,20,67,13,4.0,0.0,1.0,No,3.0
460,399,30,Female,2021-07-21 01:00:00,2021-07-21 08:00:00,7.0,0.91,28,52,20,0.0,50.0,0.0,No,0.0
461,31,24,Male,2021-08-10 00:00:00,2021-08-10 07:00:00,7.0,0.57,27,20,53,3.0,0.0,1.0,Yes,3.0

In [55]:
# Otra posibilidad es eliminar las columnas con datos faltantes, de forma de no perder participantes. ¿Cuáles son las ventajas y desventajas de esto?
datos.dropna(axis="columns")

,ID,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Smoking status
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,Yes
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,Yes
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,No
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,Yes
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,No
...,...,...,...,...,...,...,...,...,...,...,...
457,197,30,Female,2021-08-05 00:00:00,2021-08-05 08:00:00,8.0,0.94,22,63,15,Yes
458,291,54,Male,2021-01-20 22:30:00,2021-01-20 06:30:00,8.0,0.84,18,60,22,No
459,102,53,Male,2021-01-28 01:00:00,2021-01-28 09:30:00,8.5,0.71,20,67,13,No
460,399,30,Female,2021-07-21 01:00:00,2021-07-21 08:00:00,7.0,0.91,28,52,20,No
461,31,24,Male,2021-08-10 00:00:00,2021-08-10 07:00:00,7.0,0.57,27,20,53,Yes

Otra opción es hacer una combinación de estas dos posibilidades. Por ejemplo, eliminar las columnas con muchos datos faltantes (e.g. Awakenings y Caffeine compsumption) y recien luego de eso eliminar las filas que tengan algun dato perdido. 

De esa forma no pierdo tantas filas ni tantas columnas.

In [56]:
datos1 = datos.drop(columns=["Awakenings", "Caffeine consumption"])
datos2 = datos1.dropna()
datos2

# En un rato vamos a ver que hay formas más eficientes y ordenadas de encadenar comandos como estos.

,ID,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Alcohol consumption,Smoking status,Exercise frequency
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,Yes,3.0
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,Yes,3.0
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,0.0,No,3.0
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,5.0,Yes,1.0
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,No,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,197,30,Female,2021-08-05 00:00:00,2021-08-05 08:00:00,8.0,0.94,22,63,15,0.0,Yes,2.0
458,291,54,Male,2021-01-20 22:30:00,2021-01-20 06:30:00,8.0,0.84,18,60,22,0.0,No,3.0
459,102,53,Male,2021-01-28 01:00:00,2021-01-28 09:30:00,8.5,0.71,20,67,13,1.0,No,3.0
460,399,30,Female,2021-07-21 01:00:00,2021-07-21 08:00:00,7.0,0.91,28,52,20,0.0,No,0.0
461,31,24,Male,2021-08-10 00:00:00,2021-08-10 07:00:00,7.0,0.57,27,20,53,1.0,Yes,3.0

También podríamos elegir no eliminar los casos, sino reemplazar los datos faltantes con un valor (e.g. cero). A esto se lo llama "imputación de datos faltantes".

Lo podemos hacer con fillna()

In [57]:
datos.fillna(0)

,ID,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Smoking status,Exercise frequency
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,0.0,0.0,Yes,3.0
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,0.0,3.0,Yes,3.0
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,1.0,0.0,0.0,No,3.0
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,3.0,50.0,5.0,Yes,1.0
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,0.0,3.0,No,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,197,30,Female,2021-08-05 00:00:00,2021-08-05 08:00:00,8.0,0.94,22,63,15,1.0,75.0,0.0,Yes,2.0
458,291,54,Male,2021-01-20 22:30:00,2021-01-20 06:30:00,8.0,0.84,18,60,22,3.0,0.0,0.0,No,3.0
459,102,53,Male,2021-01-28 01:00:00,2021-01-28 09:30:00,8.5,0.71,20,67,13,4.0,0.0,1.0,No,3.0
460,399,30,Female,2021-07-21 01:00:00,2021-07-21 08:00:00,7.0,0.91,28,52,20,0.0,50.0,0.0,No,0.0
461,31,24,Male,2021-08-10 00:00:00,2021-08-10 07:00:00,7.0,0.57,27,20,53,3.0,0.0,1.0,Yes,3.0

In [58]:
# Chequeamos
filas_con_nan = datos.isna().any(axis=1)
datos[filas_con_nan]

,ID,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Smoking status,Exercise frequency
5,6,36,Female,2021-07-01 21:00:00,2021-07-01 04:30:00,7.5,0.90,23,60,17,0.0,NaN,0.0,No,1.0
19,20,52,Male,2021-12-03 00:30:00,2021-12-03 07:30:00,7.0,0.89,28,52,20,NaN,50.0,0.0,Yes,3.0
20,21,24,Male,2021-05-02 00:00:00,2021-05-02 08:00:00,8.0,0.83,15,75,10,3.0,0.0,NaN,No,2.0
24,25,24,Male,2021-09-16 00:00:00,2021-09-16 07:00:00,7.0,0.88,15,75,10,1.0,NaN,5.0,No,2.0
26,27,36,Female,2021-06-18 00:00:00,2021-06-18 07:00:00,7.0,0.95,28,55,17,0.0,NaN,0.0,No,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
440,441,28,Female,2021-02-06 21:00:00,2021-02-06 05:00:00,8.0,0.88,22,63,15,0.0,75.0,NaN,Yes,2.0
442,443,27,Female,2021-02-06 01:30:00,2021-02-06 08:30:00,7.0,0.68,23,22,55,1.0,NaN,4.0,No,1.0
446,447,23,Male,2021-04-21 00:00:00,2021-04-21 07:00:00,7.0,0.50,15,40,45,2.0,0.0,4.0,Yes,NaN
449,450,40,Female,2021-09-07 23:00:00,2021-09-07 07:30:00,8.5,0.55,20,32,48,1.0,NaN,3.0,Yes,0.0
454,337,50,Female,2021-07-20 22:00:00,2021-07-20 05:00:00,7.0,0.90,22,58,20,1.0,0.0,NaN,No,5.0

In [59]:
datos0 = datos.fillna(0)
datos0[filas_con_nan]

,ID,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Smoking status,Exercise frequency
5,6,36,Female,2021-07-01 21:00:00,2021-07-01 04:30:00,7.5,0.90,23,60,17,0.0,0.0,0.0,No,1.0
19,20,52,Male,2021-12-03 00:30:00,2021-12-03 07:30:00,7.0,0.89,28,52,20,0.0,50.0,0.0,Yes,3.0
20,21,24,Male,2021-05-02 00:00:00,2021-05-02 08:00:00,8.0,0.83,15,75,10,3.0,0.0,0.0,No,2.0
24,25,24,Male,2021-09-16 00:00:00,2021-09-16 07:00:00,7.0,0.88,15,75,10,1.0,0.0,5.0,No,2.0
26,27,36,Female,2021-06-18 00:00:00,2021-06-18 07:00:00,7.0,0.95,28,55,17,0.0,0.0,0.0,No,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
440,441,28,Female,2021-02-06 21:00:00,2021-02-06 05:00:00,8.0,0.88,22,63,15,0.0,75.0,0.0,Yes,2.0
442,443,27,Female,2021-02-06 01:30:00,2021-02-06 08:30:00,7.0,0.68,23,22,55,1.0,0.0,4.0,No,1.0
446,447,23,Male,2021-04-21 00:00:00,2021-04-21 07:00:00,7.0,0.50,15,40,45,2.0,0.0,4.0,Yes,0.0
449,450,40,Female,2021-09-07 23:00:00,2021-09-07 07:30:00,8.5,0.55,20,32,48,1.0,0.0,3.0,Yes,0.0
454,337,50,Female,2021-07-20 22:00:00,2021-07-20 05:00:00,7.0,0.90,22,58,20,1.0,0.0,0.0,No,5.0

¿Qué opinamos de esto? ¿Se puede usar en todos los casos? ¿Qué otras formas se te ocurren?

In [60]:
# Una forma super sencilla (pero no infalible) es reemplazar el dato perdido por la media o la mediana poblacional 
# (Capaz la mediana es mejor porque te va a buscar un dato existente)

# Ahora cual usamos??
#datos.fillna(mean)
#datos.fillna(datos.mean())

#Veamos el help... 
datos.fillna(datos.median(numeric_only=True))

,ID,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Smoking status,Exercise frequency
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,0.0,0.0,Yes,3.0
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,0.0,3.0,Yes,3.0
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,1.0,0.0,0.0,No,3.0
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,3.0,50.0,5.0,Yes,1.0
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,0.0,3.0,No,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,197,30,Female,2021-08-05 00:00:00,2021-08-05 08:00:00,8.0,0.94,22,63,15,1.0,75.0,0.0,Yes,2.0
458,291,54,Male,2021-01-20 22:30:00,2021-01-20 06:30:00,8.0,0.84,18,60,22,3.0,0.0,0.0,No,3.0
459,102,53,Male,2021-01-28 01:00:00,2021-01-28 09:30:00,8.5,0.71,20,67,13,4.0,0.0,1.0,No,3.0
460,399,30,Female,2021-07-21 01:00:00,2021-07-21 08:00:00,7.0,0.91,28,52,20,0.0,50.0,0.0,No,0.0
461,31,24,Male,2021-08-10 00:00:00,2021-08-10 07:00:00,7.0,0.57,27,20,53,3.0,0.0,1.0,Yes,3.0

In [61]:
# Tenemos que pasarle un vector de valores para usar en cada columna, el vector lo generamos asi:
datos.mean(numeric_only=True)   # No podemos tomar media de variables no-numericas

ID                        225.833333
Age                        40.222944
Sleep duration              7.470779
Sleep efficiency            0.787771
REM sleep percentage       22.614719
Deep sleep percentage      52.668831
Light sleep percentage     24.716450
Awakenings                  1.656109
Caffeine consumption       23.512586
Alcohol consumption         1.170022
Exercise frequency          1.800439
dtype: float64

Podemos resolverlo utilizando funciones que ya vimos, modificando la variable index.

In [62]:
# Esto va a funcionar?? fillna solo actúa en columnas numéricas??
datosMedia = datos.fillna(datos.mean(numeric_only=True))
datosMedia[filas_con_nan]

,ID,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Smoking status,Exercise frequency
5,6,36,Female,2021-07-01 21:00:00,2021-07-01 04:30:00,7.5,0.90,23,60,17,0.000000,23.512586,0.000000,No,1.000000
19,20,52,Male,2021-12-03 00:30:00,2021-12-03 07:30:00,7.0,0.89,28,52,20,1.656109,50.000000,0.000000,Yes,3.000000
20,21,24,Male,2021-05-02 00:00:00,2021-05-02 08:00:00,8.0,0.83,15,75,10,3.000000,0.000000,1.170022,No,2.000000
24,25,24,Male,2021-09-16 00:00:00,2021-09-16 07:00:00,7.0,0.88,15,75,10,1.000000,23.512586,5.000000,No,2.000000
26,27,36,Female,2021-06-18 00:00:00,2021-06-18 07:00:00,7.0,0.95,28,55,17,0.000000,23.512586,0.000000,No,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
440,441,28,Female,2021-02-06 21:00:00,2021-02-06 05:00:00,8.0,0.88,22,63,15,0.000000,75.000000,1.170022,Yes,2.000000
442,443,27,Female,2021-02-06 01:30:00,2021-02-06 08:30:00,7.0,0.68,23,22,55,1.000000,23.512586,4.000000,No,1.000000
446,447,23,Male,2021-04-21 00:00:00,2021-04-21 07:00:00,7.0,0.50,15,40,45,2.000000,0.000000,4.000000,Yes,1.800439
449,450,40,Female,2021-09-07 23:00:00,2021-09-07 07:30:00,8.5,0.55,20,32,48,1.000000,23.512586,3.000000,Yes,0.000000
454,337,50,Female,2021-07-20 22:00:00,2021-07-20 05:00:00,7.0,0.90,22,58,20,1.000000,0.000000,1.170022,No,5.000000

En pocas palabras:
- Completamos con 0 si pensamos que no figura el dato porque no hay o no corresponde. Por ejemplo, en información de alimentos y bebidas, el porcentaje de alcohol puede figurar como NA.
- Completamos con el promedio si pensamos que se perdió el dato y queremos afectar lo menos posible los modelos (o una técnica más avanzada sería predecir ese valor usando otras variables).

Cómo completarías estos datos faltantes?
- Metros cuadrados de un departamento.
- Cantidad de votos recibidos por un partido en la elección anterior.
- Cantidad de ventas realizadas de cierto producto en cierto día.
- Altura de un paciente.

### Ejercicio
1. Examinar el dataset de eficiencia MPG y hacer algo con los datos faltantes. ¿Qué harían si no queremos eliminar filas?
2. Examinar el dataset de pingüinos y hacer algo con los datos faltantes.

In [63]:
penguins = sns.load_dataset("penguins")
mpg = sns.load_dataset("mpg")

In [73]:
mpg.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64

In [76]:
mpg_clean = mpg.fillna(mpg.mean(numeric_only=True))
mpg_clean.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64

In [ ]:
penguins.isna().sum()
filas_con_nan_penguins = penguins.isna().any(axis=1)
penguins[filas_con_nan_penguins]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
8,Adelie,Torgersen,34.1,18.1,193.0,3475.0,NaN
9,Adelie,Torgersen,42.0,20.2,190.0,4250.0,NaN
10,Adelie,Torgersen,37.8,17.1,186.0,3300.0,NaN
11,Adelie,Torgersen,37.8,17.3,180.0,3700.0,NaN
47,Adelie,Dream,37.5,18.9,179.0,2975.0,NaN
246,Gentoo,Biscoe,44.5,14.3,216.0,4100.0,NaN
286,Gentoo,Biscoe,46.2,14.4,214.0,4650.0,NaN
324,Gentoo,Biscoe,47.3,13.8,216.0,4725.0,NaN
336,Gentoo,Biscoe,44.5,15.7,217.0,4875.0,NaN
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN

In [80]:
penguins_clean = penguins.dropna()

### 2.b Eliminar datos duplicados

En muchos casos puede suceder que haya datos duplicados en nuestro dataset. ¿Se les ocurren ejemplos?

Para identificarlos, podemos usar `duplicated()`. ¿Qué está haciendo esta función?

In [81]:
datos.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
457     True
458     True
459     True
460     True
461    False
Length: 462, dtype: bool

In [82]:
# Cuántos datos duplicados hay?
datos.duplicated().sum()

np.int64(8)

In [83]:
# Es la misma fila repetida muchas veces o varias filas duplicadas?
# Podemos usar el viejo y querido value_counts()...
datos.value_counts()

ID   Age  Gender  Bedtime              Wakeup time          Sleep duration  Sleep efficiency  REM sleep percentage  Deep sleep percentage  Light sleep percentage  Awakenings  Caffeine consumption  Alcohol consumption  Smoking status  Exercise frequency
102  53   Male    2021-01-28 01:00:00  2021-01-28 09:30:00  8.5             0.71              20                    67                     13                      4.0         0.0                   1.0                  No              3.0                   2
154  41   Male    2021-07-01 02:30:00  2021-07-01 10:00:00  7.5             0.70              22                    59                     19                      3.0         0.0                   0.0                  No              3.0                   2
197  30   Female  2021-08-05 00:00:00  2021-08-05 08:00:00  8.0             0.94              22                    63                     15                      1.0         75.0                  0.0                  Yes             2.0                   2
291  54   Male    2021-01-20 22:30:00  2021-01-20 06:30:00  8.0             0.84              18                    60                     22                      3.0         0.0                   0.0                  No              3.0                   2
300  22   Male    2021-04-24 21:30:00  2021-04-24 05:30:00  8.0             0.60              27                    20                     53                      4.0         0.0                   4.0                  No              3.0                   2
                                                                                                                                                                                                                                                               ..
449  52   Male    2021-03-31 21:00:00  2021-03-31 03:00:00  6.0             0.74              28                    57                     15                      4.0         25.0                  0.0                  No              3.0                   1
451  45   Male    2021-07-29 21:00:00  2021-07-29 04:00:00  7.0             0.76              18                    72                     10                      3.0         0.0                   0.0                  No              3.0                   1
452  18   Male    2021-03-17 02:30:00  2021-03-17 10:00:00  7.5             0.63              22                    23                     55                      1.0         50.0                  0.0                  No              1.0                   1
40   58   Female  2021-03-26 02:00:00  2021-03-26 09:00:00  7.0             0.63              22                    23                     55                      3.0         50.0                  3.0                  No              0.0                   1
31   24   Male    2021-08-10 00:00:00  2021-08-10 07:00:00  7.0             0.57              27                    20                     53                      3.0         0.0                   1.0                  Yes             3.0                   1
Name: count, Length: 390, dtype: int64

Para eliminarlos, podríamos usar `drop_duplicates()`

In [84]:
# O vemos las filas
datos[datos.duplicated()]

# O keep = False para ver todas las filas duplicadas, todas las veces que aparecen
datos[datos.duplicated(keep = False)]

,ID,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Smoking status,Exercise frequency
101,102,53,Male,2021-01-28 01:00:00,2021-01-28 09:30:00,8.5,0.71,20,67,13,4.0,0.0,1.0,No,3.0
153,154,41,Male,2021-07-01 02:30:00,2021-07-01 10:00:00,7.5,0.70,22,59,19,3.0,0.0,0.0,No,3.0
196,197,30,Female,2021-08-05 00:00:00,2021-08-05 08:00:00,8.0,0.94,22,63,15,1.0,75.0,0.0,Yes,2.0
290,291,54,Male,2021-01-20 22:30:00,2021-01-20 06:30:00,8.0,0.84,18,60,22,3.0,0.0,0.0,No,3.0
299,300,22,Male,2021-04-24 21:30:00,2021-04-24 05:30:00,8.0,0.60,27,20,53,4.0,0.0,4.0,No,3.0
332,333,12,Female,2021-11-01 01:00:00,2021-11-01 10:00:00,9.0,0.56,18,35,47,1.0,0.0,0.0,No,0.0
336,337,50,Female,2021-07-20 22:00:00,2021-07-20 05:00:00,7.0,0.90,22,58,20,1.0,0.0,NaN,No,5.0
398,399,30,Female,2021-07-21 01:00:00,2021-07-21 08:00:00,7.0,0.91,28,52,20,0.0,50.0,0.0,No,0.0
452,300,22,Male,2021-04-24 21:30:00,2021-04-24 05:30:00,8.0,0.60,27,20,53,4.0,0.0,4.0,No,3.0
454,337,50,Female,2021-07-20 22:00:00,2021-07-20 05:00:00,7.0,0.90,22,58,20,1.0,0.0,NaN,No,5.0
455,333,12,Female,2021-11-01 01:00:00,2021-11-01 10:00:00,9.0,0.56,18,35,47,1.0,0.0,0.0,No,0.0
456,154,41,Male,2021-07-01 02:30:00,2021-07-01 10:00:00,7.5,0.70,22,59,19,3.0,0.0,0.0,No,3.0
457,197,30,Female,2021-08-05 00:00:00,2021-08-05 08:00:00,8.0,0.94,22,63,15,1.0,75.0,0.0,Yes,2.0
458,291,54,Male,2021-01-20 22:30:00,2021-01-20 06:30:00,8.0,0.84,18,60,22,3.0,0.0,0.0,No,3.0
459,102,53,Male,2021-01-28 01:00:00,2021-01-28 09:30:00,8.5,0.71,20,67,13,4.0,0.0,1.0,No,3.0
460,399,30,Female,2021-07-21 01:00:00,2021-07-21 08:00:00,7.0,0.91,28,52,20,0.0,50.0,0.0,No,0.0

In [85]:
# Eliminamos duplicados
datos.drop_duplicates()

,ID,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Smoking status,Exercise frequency
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,0.0,0.0,Yes,3.0
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,0.0,3.0,Yes,3.0
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,1.0,0.0,0.0,No,3.0
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,3.0,50.0,5.0,Yes,1.0
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,0.0,3.0,No,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
449,450,40,Female,2021-09-07 23:00:00,2021-09-07 07:30:00,8.5,0.55,20,32,48,1.0,NaN,3.0,Yes,0.0
450,451,45,Male,2021-07-29 21:00:00,2021-07-29 04:00:00,7.0,0.76,18,72,10,3.0,0.0,0.0,No,3.0
451,452,18,Male,2021-03-17 02:30:00,2021-03-17 10:00:00,7.5,0.63,22,23,55,1.0,50.0,0.0,No,1.0
453,40,58,Female,2021-03-26 02:00:00,2021-03-26 09:00:00,7.0,0.63,22,23,55,3.0,50.0,3.0,No,0.0
461,31,24,Male,2021-08-10 00:00:00,2021-08-10 07:00:00,7.0,0.57,27,20,53,3.0,0.0,1.0,Yes,3.0

¿Qué hace esta función? ¿Qué valores se queda y cuáles elimina?

Por defecto, se queda con el primer caso, pero podemos indicarle que se quede con el último por ej:

In [86]:
datos.drop_duplicates(keep = "last")

,ID,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Smoking status,Exercise frequency
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,0.0,0.0,Yes,3.0
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,0.0,3.0,Yes,3.0
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,1.0,0.0,0.0,No,3.0
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,3.0,50.0,5.0,Yes,1.0
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,0.0,3.0,No,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,197,30,Female,2021-08-05 00:00:00,2021-08-05 08:00:00,8.0,0.94,22,63,15,1.0,75.0,0.0,Yes,2.0
458,291,54,Male,2021-01-20 22:30:00,2021-01-20 06:30:00,8.0,0.84,18,60,22,3.0,0.0,0.0,No,3.0
459,102,53,Male,2021-01-28 01:00:00,2021-01-28 09:30:00,8.5,0.71,20,67,13,4.0,0.0,1.0,No,3.0
460,399,30,Female,2021-07-21 01:00:00,2021-07-21 08:00:00,7.0,0.91,28,52,20,0.0,50.0,0.0,No,0.0
461,31,24,Male,2021-08-10 00:00:00,2021-08-10 07:00:00,7.0,0.57,27,20,53,3.0,0.0,1.0,Yes,3.0

**Pregunta:** Si tuvieramos sujetos duplicados, es decir, completaron dos veces la misma encuesta, pero respondieron distinto, cómo lo podríamos saber?

### 2.c Resetear el index

Volvamos a los pingüinos.
Una vez que eliminamos filas por el motivo que sea, nos van a quedar índices salteados. En muchos casos no es importante conservar los índices originales, y es conveniente numerar todo de 0 a N-1.

In [87]:
penguinsClean = penguins.dropna()
penguinsClean

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male
...,...,...,...,...,...,...,...
338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,Female
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [88]:
# Reseteamos los índices 
penguinsClean = penguinsClean.reset_index()
penguinsClean   # Vemos que creó una nueva columna con los índices viejos

,index,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
4,5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male
...,...,...,...,...,...,...,...,...
328,338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,Female
329,340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
330,341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
331,342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
332,343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [89]:
# De esta forma solo nos quedamos con lo síndices nuevos.
penguinsClean = penguinsClean.reset_index(drop = True)
penguinsClean

,index,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
4,5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male
...,...,...,...,...,...,...,...,...
328,338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,Female
329,340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
330,341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
331,342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
332,343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [90]:
# No funciono??
# Es que tenemos que empezar todo de nuevo!

penguinsClean = penguins.dropna()
penguinsClean = penguinsClean.reset_index(drop = True)
penguinsClean

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
4,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male
...,...,...,...,...,...,...,...
328,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,Female
329,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
330,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
331,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
332,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

## Encadenar todos estos métodos

Esta forma de ir modificando un dataset no es muy práctica.

Por ejemplo si ejecutamos varias veces el mismo comando, obtendremos cada vez algo distinto.

Una solución es encadenar métodos para hacer el código más legible y fácil de reusar. Y más eficiente también.

In [91]:
penguinsClean = penguins.dropna().reset_index()
penguinsClean.head()

,index,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
4,5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male

In [92]:
# Si queremos eliminar la columna de índices viejos
penguinsClean = penguins.dropna().reset_index(drop = True)
penguinsClean.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
4,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male

In [93]:
# Ahora sumamos 1 a todos los indices
penguinsClean.index += 1
penguinsClean.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
1,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
2,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
3,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male

Podemos encadenar estas operaciones?

In [ ]:
#penguinsClean = penguins.dropna().reset_index(drop = True).index += 1  nop

In [94]:
# Eso dio error. Y así?
penguins.dropna().reset_index(drop = True).index += 1
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

No sabemos dónde lo guardó...

Para encadenar esta operación vamos a utilizar `.rename(index = dict o function)`.

Podemos pasarle también un diccionario o una función.

### Ejercicio 
1. Cambiar el índice 0 a "Cero".
2. Tomas la raíz cuadradada de los índices (del dataset penguinsClean original sin "Cero").

In [95]:
penguinsClean = penguins.dropna().reset_index(drop = True)
penguinsClean.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
4,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male

In [96]:
penguinsCleanCero = penguinsClean.rename(index={0:"Cero"})
penguinsCleanCero

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
Cero,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
4,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male
...,...,...,...,...,...,...,...
328,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,Female
329,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
330,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
331,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
332,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [101]:
import math

penguinsClean = penguinsClean.reset_index(drop = True)
penguinsClean = penguinsClean.rename(index= lambda x: math.sqrt(x))

penguinsClean

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0.000000,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1.000000,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
1.414214,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
1.732051,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
2.000000,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male
...,...,...,...,...,...,...,...
18.110770,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,Female
18.138357,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
18.165902,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
18.193405,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
18.220867,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

### Ejemplo: sumar uno a todos los índices

Para sumar uno a todos los índices no podemos hacer penguinsClean.rename(index = + 1).

Podemos definir primero nuestra propia función.

In [106]:
def sumaUno(x):
    return(x+1)
penguinsClean= penguinsClean.reset_index(drop=True)
penguinsClean.rename(index = sumaUno)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
1,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
2,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
3,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male
...,...,...,...,...,...,...,...
329,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,Female
330,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
331,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
332,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
333,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

## 3. Funciones lambda
Resulta engorroso definir una función para usarla solamente dentro del rename. 

Las **funciones lambda** nos permiten definir funciones anónimas "al vuelo".

La sintaxis es

`lambda arguments : expression`

In [108]:
# Ejemplo
x = lambda a : a + 10
print(x(5))

15

In [109]:
# Ejemplo
x = lambda a, b : a * b
print(x(5, 6))

30

In [110]:
# Ejemplo
x = lambda a : a + 1
print(x(5))

6

In [111]:
# Ahora sí!
penguinsClean.rename(index = lambda a : a + 1)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
1,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
2,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
3,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male
...,...,...,...,...,...,...,...
329,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,Female
330,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
331,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
332,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
333,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

Esta operación la podemos encadenar con las anteriores:

In [112]:
penguinsClean = penguins.dropna().reset_index(drop = True).rename(index = lambda a : a + 1)
penguinsClean.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
1,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
2,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
3,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male

In [113]:
# O si queremos cada metodo en una linea nueva
penguinsClean = (
    penguins.dropna()
    .reset_index(drop = True)
    .rename(index = lambda a : a + 1)
)
penguinsClean.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
1,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
2,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
3,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male

### Ejercicio
Utilizando funciones lambda:
1. Encadenar un método más para agregar "_orig" a los nombres de todas las columnas.
2. Encadenar un método más para reemplazar todos _ por - en los nombres de columnas.

In [114]:
# Sugerencia 1
"hola" + "chau"

'holachau'

In [115]:
# Sugerencia 2
str.replace("abcndjaA", "a", "oo")

'oobcndjooA'

In [119]:
agregar_orig = lambda x: x + "_orig"
reemplazar_= lambda x: str.replace(x,"_","-")

penguinsClean.head()
penguinsClean.rename(columns=agregar_orig).rename(columns=reemplazar_)

,species-orig,island-orig,bill-length-mm-orig,bill-depth-mm-orig,flipper-length-mm-orig,body-mass-g-orig,sex-orig
1,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
2,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
3,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male
...,...,...,...,...,...,...,...
329,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,Female
330,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
331,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
332,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
333,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male