In [43]:
import seaborn as sns
from sklearn.model_selection import KFold
import matplotlib.pyplot as plt

from scipy import stats
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from formulaic import model_matrix

In [44]:
#import os
#print(pwd)
#os.chdir('./notebooks')

## 4. Listas por comprensión

**Ejemplo:** Queremos cargar el siguiente dataset de variables de oferta y demanda nacional y generar un nuevo dataset que contenga sólo las variables de oferta (las que comienzan con "Oferta").

¿Cómo podemos hacerlo?

In [45]:
macro = pd.read_csv("OfertaYDemanda.csv")
macro.head()

,ano,pbi,OfertaAgricultura,OfertaMinas,OfertaManufacturera,OfertaElectricidad,OfertaConstruccion,OfertaComercio,OfertaTransporte,OfertaFinaciera,...,DemandaConsumoHogares,DemandaConsumoGobiertano,DemandaConstrucciones,DemandaMaterialNacional,DemandaMaterialImportada,DemandaMaquinariaNacional,DemandaMaquinariaImportaciones,DemandaExportaciones,DemandaImportaciones,DemandaGib
0,1950,142098481044,13696637358,1452011417,32304751942,198218385,5918090281,25281650565,7262970408,19550757718,...,104655579712,21706316451,20353627362,668586865,584400198,3119383475,863112352,10729585056,14039465296,142098481044
1,1951,147436076837,14629457210,1686941522,33149279696,212725994,6060937395,26260862055,7534071597,19902737804,...,110537717447,21767097618,21739314091,842740200,2532757698,3562534310,1292775007,8455493993,15744444593,147436076837
2,1952,140491256038,12545616104,1794762161,32522906863,227896262,5571363747,24417324287,7017131008,20598804008,...,105108053681,21455589059,19685428171,1119084065,1484421674,3440750327,1088415946,6224082425,11637586183,140491256038
3,1953,147324304004,16402296333,1925706862,32341045582,242404261,5546340195,24009746257,7210541490,20716225895,...,106402901621,20742065172,20237375978,1207890913,1459988875,3621895632,886926720,9619869463,9626750804,147324304004
4,1954,153315563451,16308747029,2037374129,34903529762,263839496,5308705373,25492912808,7558082163,21278479393,...,114392396415,21238933697,19372130307,1173451578,805900196,4121320340,783079947,10201623290,12506287869,153315563451

In [46]:
macro.info()

<class 'pandas.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 22 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   ano                             66 non-null     int64
 1   pbi                             66 non-null     int64
 2   OfertaAgricultura               66 non-null     int64
 3   OfertaMinas                     66 non-null     int64
 4   OfertaManufacturera             66 non-null     int64
 5   OfertaElectricidad              66 non-null     int64
 6   OfertaConstruccion              66 non-null     int64
 7   OfertaComercio                  66 non-null     int64
 8   OfertaTransporte                66 non-null     int64
 9   OfertaFinaciera                 66 non-null     int64
 10  OfertaSociales                  66 non-null     int64
 11  OfertaImpuestos                 66 non-null     int64
 12  DemandaConsumoHogares           66 non-null     int64
 13  DemandaConsumoGobiertano        66 non-null     int64
 14  DemandaConstrucciones           66 non-null     int64
 15  DemandaMaterialNacional         66 non-null     int64
 16  DemandaMaterialImportada        66 non-null     int64
 17  DemandaMaquinariaNacional       66 non-null     int64
 18  DemandaMaquinariaImportaciones  66 non-null     int64
 19  DemandaExportaciones            66 non-null     int64
 20  DemandaImportaciones            66 non-null     int64
 21  DemandaGib                      66 non-null     int64
dtypes: int64(22)
memory usage: 11.5 KB

Para quedarnos con algunas columnas no necesitamos ningún comando especial, solo pasarle la lista de columnas que queremos.

In [47]:
# Ejemplo. Si queremos solo las variables ano y pbi...
ano_pbi = macro[["ano","pbi"]]

ano_pbi

     ano           pbi
0   1950  142098481044
1   1951  147436076837
2   1952  140491256038
3   1953  147324304004
4   1954  153315563451
..   ...           ...
61  2011  711876372894
62  2012  706420870168
63  2013  722040183987
64  2014  705611747648
65  2015  722561538316

[66 rows x 2 columns]

¿Cómo generamos una lista con las columnas que comienzan con "Oferta"?

In [48]:
# De esta lista queremos quedarnos con las variables de oferta
macro.columns

Index(['ano', 'pbi', 'OfertaAgricultura', 'OfertaMinas', 'OfertaManufacturera',
       'OfertaElectricidad', 'OfertaConstruccion', 'OfertaComercio',
       'OfertaTransporte', 'OfertaFinaciera', 'OfertaSociales',
       'OfertaImpuestos', 'DemandaConsumoHogares', 'DemandaConsumoGobiertano',
       'DemandaConstrucciones', 'DemandaMaterialNacional',
       'DemandaMaterialImportada', 'DemandaMaquinariaNacional',
       'DemandaMaquinariaImportaciones', 'DemandaExportaciones',
       'DemandaImportaciones', 'DemandaGib'],
      dtype='str')

Definimos **listas por comprensión**.

### A. Sintaxis básica

`[f(x) for x in LISTA]`

In [49]:
# Ejemplo
[x + 1 for x in [2, 3, 5]]

[3, 4, 6]

In [50]:
# Ejemplo
# Si queremos agregarle _orig a todas las variables
[x+"_orig" for x in macro.columns]

['ano_orig',
 'pbi_orig',
 'OfertaAgricultura_orig',
 'OfertaMinas_orig',
 'OfertaManufacturera_orig',
 'OfertaElectricidad_orig',
 'OfertaConstruccion_orig',
 'OfertaComercio_orig',
 'OfertaTransporte_orig',
 'OfertaFinaciera_orig',
 'OfertaSociales_orig',
 'OfertaImpuestos_orig',
 'DemandaConsumoHogares_orig',
 'DemandaConsumoGobiertano_orig',
 'DemandaConstrucciones_orig',
 'DemandaMaterialNacional_orig',
 'DemandaMaterialImportada_orig',
 'DemandaMaquinariaNacional_orig',
 'DemandaMaquinariaImportaciones_orig',
 'DemandaExportaciones_orig',
 'DemandaImportaciones_orig',
 'DemandaGib_orig']

In [51]:
# Que hace este comando?
[col[:2] for col in macro.columns]

# Recordar que un string es una sequencia de caracteres.

['an',
 'pb',
 'Of',
 'Of',
 'Of',
 'Of',
 'Of',
 'Of',
 'Of',
 'Of',
 'Of',
 'Of',
 'De',
 'De',
 'De',
 'De',
 'De',
 'De',
 'De',
 'De',
 'De',
 'De']

**Ejercicio:** Convertir todos los nombres de columnas del DataFrame macro a mayúsculas usando listas por comprensión (reemplazar los nombres en el DataFrame, no solo generar la lista).

In [52]:
macro_mayus= macro.copy()
macro_mayus.columns= [str.upper(x) for x in macro_mayus.columns]
macro_mayus

,ANO,PBI,OFERTAAGRICULTURA,OFERTAMINAS,OFERTAMANUFACTURERA,OFERTAELECTRICIDAD,OFERTACONSTRUCCION,OFERTACOMERCIO,OFERTATRANSPORTE,OFERTAFINACIERA,...,DEMANDACONSUMOHOGARES,DEMANDACONSUMOGOBIERTANO,DEMANDACONSTRUCCIONES,DEMANDAMATERIALNACIONAL,DEMANDAMATERIALIMPORTADA,DEMANDAMAQUINARIANACIONAL,DEMANDAMAQUINARIAIMPORTACIONES,DEMANDAEXPORTACIONES,DEMANDAIMPORTACIONES,DEMANDAGIB
0,1950,142098481044,13696637358,1452011417,32304751942,198218385,5918090281,25281650565,7262970408,19550757718,...,104655579712,21706316451,20353627362,668586865,584400198,3119383475,863112352,10729585056,14039465296,142098481044
1,1951,147436076837,14629457210,1686941522,33149279696,212725994,6060937395,26260862055,7534071597,19902737804,...,110537717447,21767097618,21739314091,842740200,2532757698,3562534310,1292775007,8455493993,15744444593,147436076837
2,1952,140491256038,12545616104,1794762161,32522906863,227896262,5571363747,24417324287,7017131008,20598804008,...,105108053681,21455589059,19685428171,1119084065,1484421674,3440750327,1088415946,6224082425,11637586183,140491256038
3,1953,147324304004,16402296333,1925706862,32341045582,242404261,5546340195,24009746257,7210541490,20716225895,...,106402901621,20742065172,20237375978,1207890913,1459988875,3621895632,886926720,9619869463,9626750804,147324304004
4,1954,153315563451,16308747029,2037374129,34903529762,263839496,5308705373,25492912808,7558082163,21278479393,...,114392396415,21238933697,19372130307,1173451578,805900196,4121320340,783079947,10201623290,12506287869,153315563451
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,2011,711876372894,51232247600,23624757639,132833552973,11137192032,22917469985,109669382185,52052730045,98166614131,...,501468174468,80184420870,66813943052,11899022232,7661349361,23759578339,41326728494,159841680179,190143785790,709846118754
62,2012,706420870168,44579958519,23338178766,128887568646,11655890977,22357980999,107013302114,52391956399,99767726112,...,499877233083,82549920556,64700327691,11937482081,5518154212,21650676546,35683290813,153186765485,181049138448,704517238544
63,2013,722040183987,49721752068,22404030031,130944551380,11717769879,22344881459,109388604371,53702369755,100256426891,...,516595596894,86152836238,64634666531,13783168151,7239125008,24156151830,33736431348,146449825751,186368215953,720649972746
64,2014,705611747648,51321551605,22736711813,124263314517,11939156363,21877578423,102335931469,54087653912,98874388852,...,496730426540,89033326375,63301703123,10305735713,5950583136,21378949359,32538397909,136756102482,165611660510,703337679146
65,2015,722561538316,54675970819,23375961951,124566831310,12346924852,22521998699,104976597217,55417987930,100687552693,...,509870708731,94456349868,64462175043,11439762277,5599292920,24228907045,34412887620,135515134091,173984203797,722845994518

**Ojo:** No puedo aplicar funciones en el nombre de la variable.

In [53]:
# Ejemplo. Esto funcionará?
[np.sqrt(x) for x**2 in np.arange(1,10)]

SyntaxError: cannot assign to expression (2404129098.py, line 2)

### B. Seleccionar solo los valores que cumplen una condición.

En este caso usamos la sintaxis

`[x for x in LISTA if CONDICION]`

In [54]:
# Ejemplo
[x for x in ["hola", "saludos", "chau"] if len(x) == 4]

['hola', 'chau']

In [55]:
# Ejemplo
[x for x in np.arange(1,10) if x % 2 == 0]   # np.arange nos da todos los enteros desde 1 a 10 (exclusive)

[np.int64(2), np.int64(4), np.int64(6), np.int64(8)]

In [56]:
# Ejemplo
# Podemos también aplicar una función a los valores que cumplen la condición
[x**2 for x in np.arange(1,10) if x % 2 == 0]   # np.arange nos da todos los enteros desde 1 a 10 (exclusive)

[np.int64(4), np.int64(16), np.int64(36), np.int64(64)]

**Ejercicio:**
Generar una lista con todas los nombres de variables que comienzan con "Oferta".

In [57]:
macro.columns

Index(['ano', 'pbi', 'OfertaAgricultura', 'OfertaMinas', 'OfertaManufacturera',
       'OfertaElectricidad', 'OfertaConstruccion', 'OfertaComercio',
       'OfertaTransporte', 'OfertaFinaciera', 'OfertaSociales',
       'OfertaImpuestos', 'DemandaConsumoHogares', 'DemandaConsumoGobiertano',
       'DemandaConstrucciones', 'DemandaMaterialNacional',
       'DemandaMaterialImportada', 'DemandaMaquinariaNacional',
       'DemandaMaquinariaImportaciones', 'DemandaExportaciones',
       'DemandaImportaciones', 'DemandaGib'],
      dtype='str')

In [59]:
columnas_oferta= [x for x in macro.columns if x.startswith("Oferta")]

columnas_oferta

['OfertaAgricultura',
 'OfertaMinas',
 'OfertaManufacturera',
 'OfertaElectricidad',
 'OfertaConstruccion',
 'OfertaComercio',
 'OfertaTransporte',
 'OfertaFinaciera',
 'OfertaSociales',
 'OfertaImpuestos']

**Ejercicio:**
Generar un DataFrame que contenga solo las variables de Oferta.

In [61]:
macro_ofertas = macro[columnas_oferta]

macro_ofertas.head()

,OfertaAgricultura,OfertaMinas,OfertaManufacturera,OfertaElectricidad,OfertaConstruccion,OfertaComercio,OfertaTransporte,OfertaFinaciera,OfertaSociales,OfertaImpuestos
0,13696637358,1452011417,32304751942,198218385,5918090281,25281650565,7262970408,19550757718,21743658464,14697709118
1,14629457210,1686941522,33149279696,212725994,6060937395,26260862055,7534071597,19902737804,22368440435,15394949124
2,12545616104,1794762161,32522906863,227896262,5571363747,24417324287,7017131008,20598804008,22577377299,14648699492
3,16402296333,1925706862,32341045582,242404261,5546340195,24009746257,7210541490,20716225895,23072219963,15257871308
4,16308747029,2037374129,34903529762,263839496,5308705373,25492912808,7558082163,21278479393,23797814592,16078311792

Podemos hacerlo también con `.startswith()`

In [62]:
macroOferta = macro[[col for col in macro.columns if col.startswith("Oferta")]]
macroOferta.head()

,OfertaAgricultura,OfertaMinas,OfertaManufacturera,OfertaElectricidad,OfertaConstruccion,OfertaComercio,OfertaTransporte,OfertaFinaciera,OfertaSociales,OfertaImpuestos
0,13696637358,1452011417,32304751942,198218385,5918090281,25281650565,7262970408,19550757718,21743658464,14697709118
1,14629457210,1686941522,33149279696,212725994,6060937395,26260862055,7534071597,19902737804,22368440435,15394949124
2,12545616104,1794762161,32522906863,227896262,5571363747,24417324287,7017131008,20598804008,22577377299,14648699492
3,16402296333,1925706862,32341045582,242404261,5546340195,24009746257,7210541490,20716225895,23072219963,15257871308
4,16308747029,2037374129,34903529762,263839496,5308705373,25492912808,7558082163,21278479393,23797814592,16078311792

**Ejercicio:** Al DataFrame de Oferta agregar una columna OfertaAgregada que contenga la suma total de la oferta.

In [63]:
macroOferta["OfertaAgregada"] = macroOferta.sum(axis=1)
macroOferta.head()

,OfertaAgricultura,OfertaMinas,OfertaManufacturera,OfertaElectricidad,OfertaConstruccion,OfertaComercio,OfertaTransporte,OfertaFinaciera,OfertaSociales,OfertaImpuestos,OfertaAgregada
0,13696637358,1452011417,32304751942,198218385,5918090281,25281650565,7262970408,19550757718,21743658464,14697709118,142106455656
1,14629457210,1686941522,33149279696,212725994,6060937395,26260862055,7534071597,19902737804,22368440435,15394949124,147200402832
2,12545616104,1794762161,32522906863,227896262,5571363747,24417324287,7017131008,20598804008,22577377299,14648699492,141921881231
3,16402296333,1925706862,32341045582,242404261,5546340195,24009746257,7210541490,20716225895,23072219963,15257871308,146724398146
4,16308747029,2037374129,34903529762,263839496,5308705373,25492912808,7558082163,21278479393,23797814592,16078311792,153027796537

**Ejemplo:** Generar un DataFrame eliminando todas las columnas de Demanda y dejando solo una columna DemandaAgregada con la suma de toda la demanda.

Sugerencia: para eliminar columnas usamos `.drop([LISTA de COLUMNAS], axis = 1)`

In [64]:
# Primero generamos la serie de DemandaAgregada
demandaAgregada = macro[[col for col in macro.columns if col.startswith("Demanda")]].sum(axis=1)
demandaAgregada

0      318818537811
1      333910951794
2      311734667569
3      321129969182
4      337910687090
          ...
61    1792944801539
62    1760670227459
63    1799765990450
64    1724944564293
65    1776815415910
Length: 66, dtype: int64

In [65]:
# Ahora creamos un dataframe con las columnas eliminadas
macroAgregada = macro.drop([col for col in macro.columns if col.startswith("Demanda")], axis = 1)
macroAgregada#

,ano,pbi,OfertaAgricultura,OfertaMinas,OfertaManufacturera,OfertaElectricidad,OfertaConstruccion,OfertaComercio,OfertaTransporte,OfertaFinaciera,OfertaSociales,OfertaImpuestos
0,1950,142098481044,13696637358,1452011417,32304751942,198218385,5918090281,25281650565,7262970408,19550757718,21743658464,14697709118
1,1951,147436076837,14629457210,1686941522,33149279696,212725994,6060937395,26260862055,7534071597,19902737804,22368440435,15394949124
2,1952,140491256038,12545616104,1794762161,32522906863,227896262,5571363747,24417324287,7017131008,20598804008,22577377299,14648699492
3,1953,147324304004,16402296333,1925706862,32341045582,242404261,5546340195,24009746257,7210541490,20716225895,23072219963,15257871308
4,1954,153315563451,16308747029,2037374129,34903529762,263839496,5308705373,25492912808,7558082163,21278479393,23797814592,16078311792
...,...,...,...,...,...,...,...,...,...,...,...,...
61,2011,711876372894,51232247600,23624757639,132833552973,11137192032,22917469985,109669382185,52052730045,98166614131,93837237783,118208323319
62,2012,706420870168,44579958519,23338178766,128887568646,11655890977,22357980999,107013302114,52391956399,99767726112,97055804064,119116971045
63,2013,722040183987,49721752068,22404030031,130944551380,11717769879,22344881459,109388604371,53702369755,100256426891,98923181463,123021130374
64,2014,705611747648,51321551605,22736711813,124263314517,11939156363,21877578423,102335931469,54087653912,98874388852,100532401097,115972956704
65,2015,722561538316,54675970819,23375961951,124566831310,12346924852,22521998699,104976597217,55417987930,100687552693,103292786749,118778641731

In [67]:
# Finalmente agregamos la columna "DemandaAgregada"
macroAgregada["DemandaAgregada"] = demandaAgregada

macroAgregada

,ano,pbi,OfertaAgricultura,OfertaMinas,OfertaManufacturera,OfertaElectricidad,OfertaConstruccion,OfertaComercio,OfertaTransporte,OfertaFinaciera,OfertaSociales,OfertaImpuestos,DemandaAgregada
0,1950,142098481044,13696637358,1452011417,32304751942,198218385,5918090281,25281650565,7262970408,19550757718,21743658464,14697709118,318818537811
1,1951,147436076837,14629457210,1686941522,33149279696,212725994,6060937395,26260862055,7534071597,19902737804,22368440435,15394949124,333910951794
2,1952,140491256038,12545616104,1794762161,32522906863,227896262,5571363747,24417324287,7017131008,20598804008,22577377299,14648699492,311734667569
3,1953,147324304004,16402296333,1925706862,32341045582,242404261,5546340195,24009746257,7210541490,20716225895,23072219963,15257871308,321129969182
4,1954,153315563451,16308747029,2037374129,34903529762,263839496,5308705373,25492912808,7558082163,21278479393,23797814592,16078311792,337910687090
...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,2011,711876372894,51232247600,23624757639,132833552973,11137192032,22917469985,109669382185,52052730045,98166614131,93837237783,118208323319,1792944801539
62,2012,706420870168,44579958519,23338178766,128887568646,11655890977,22357980999,107013302114,52391956399,99767726112,97055804064,119116971045,1760670227459
63,2013,722040183987,49721752068,22404030031,130944551380,11717769879,22344881459,109388604371,53702369755,100256426891,98923181463,123021130374,1799765990450
64,2014,705611747648,51321551605,22736711813,124263314517,11939156363,21877578423,102335931469,54087653912,98874388852,100532401097,115972956704,1724944564293
65,2015,722561538316,54675970819,23375961951,124566831310,12346924852,22521998699,104976597217,55417987930,100687552693,103292786749,118778641731,1776815415910

**Ejemplo:** Generar un DataFrame que contenga: año, pbi, OfertaSuma y DemandaSuma.

In [74]:
# Podemos usar concat para pegar columnas en un data frame (alinea los datos con mismo índice)
ofertaAgregada = macro[[col for col in macro.columns if col.startswith("Oferta")]].sum(axis=1)
demandaAgregada = macro[[col for col in macro.columns if col.startswith("Demanda")]].sum(axis=1)

macroResumen = pd.concat([
    macro[["ano", "pbi"]],
    ofertaAgregada,
    demandaAgregada,
], axis=1)

macroResumen.head()

    ano           pbi             0             1
0  1950  142098481044  142106455656  318818537811
1  1951  147436076837  147200402832  333910951794
2  1952  140491256038  141921881231  311734667569
3  1953  147324304004  146724398146  321129969182
4  1954  153315563451  153027796537  337910687090

In [78]:
# Ejercicio: ajustar el ejercicio anterior para que las columnas se llamen "OfertaAgregada" y "DemandaAgregada".
macroResumen_fix = macroResumen.rename(columns={0:"OfertaAgregada",1:"DemandaAgregada"})
macroResumen_fix

     ano           pbi  OfertaAgregada  DemandaAgregada
0   1950  142098481044    142106455656     318818537811
1   1951  147436076837    147200402832     333910951794
2   1952  140491256038    141921881231     311734667569
3   1953  147324304004    146724398146     321129969182
4   1954  153315563451    153027796537     337910687090
..   ...           ...             ...              ...
61  2011  711876372894    713679507692    1792944801539
62  2012  706420870168    706165337641    1760670227459
63  2013  722040183987    722424697671    1799765990450
64  2014  705611747648    703941644755    1724944564293
65  2015  722561538316    720641253951    1776815415910

[66 rows x 4 columns]

### C. Aplicar funciones distintas según alguna condición.

La función que usamos para listas por comprensión es una función lambda `(lambda x : f(x))`, pero solo ponemos f(x).

La funciones lambda permiten usar condiciones if de la siguiente forma para definir funciones partidas

`lambda x : f(x) if CONDICION else g(x)`

**Ejercicio:** Implementar la siguiente funcion como función lambda:
$$
 f(x)= 
\begin{cases}
x + 1 & \text{if } x \geq 2 \\
x^2   & \text{if } x < 2
\end{cases}
$$

In [79]:
partida = lambda x: x+1 if x>=2 else x**2

In [ ]:
partida(1)

1

In [82]:
partida(3)

4

**Ejemplo.** Queremos agregar "Super" adelante de todas las variables de Oferta.

Para listas por comprensión usamos la sintaxis

`[f(x) if CONDICION else g(x) for x in LISTA]`

Acá `f(x) if CONDICION else g(x)` es una función lambda.

In [83]:
# Ejemplo. Qué hace el siguiente comando?
[x / 2 if (x % 2 == 0) else x for x in np.arange(1,10)]   # np.arange nos da todos los enteros desde 1 a 10 (exclusive)

[np.int64(1),
 np.float64(1.0),
 np.int64(3),
 np.float64(2.0),
 np.int64(5),
 np.float64(3.0),
 np.int64(7),
 np.float64(4.0),
 np.int64(9)]

**Nota:** Comparar con el if que habiamos usado antes en listas por comprensión, ¿cuál es la diferencia?

**Ejercicio.**
Convertir todos los nombres de columnas de Oferta a mayúsculas.

In [86]:
macroAgregada.columns = [str.upper(x) if (x.startswith("Oferta")) else x for x in macroAgregada.columns]

macroAgregada

,ano,pbi,OFERTAAGRICULTURA,OFERTAMINAS,OFERTAMANUFACTURERA,OFERTAELECTRICIDAD,OFERTACONSTRUCCION,OFERTACOMERCIO,OFERTATRANSPORTE,OFERTAFINACIERA,OFERTASOCIALES,OFERTAIMPUESTOS,DemandaAgregada
0,1950,142098481044,13696637358,1452011417,32304751942,198218385,5918090281,25281650565,7262970408,19550757718,21743658464,14697709118,318818537811
1,1951,147436076837,14629457210,1686941522,33149279696,212725994,6060937395,26260862055,7534071597,19902737804,22368440435,15394949124,333910951794
2,1952,140491256038,12545616104,1794762161,32522906863,227896262,5571363747,24417324287,7017131008,20598804008,22577377299,14648699492,311734667569
3,1953,147324304004,16402296333,1925706862,32341045582,242404261,5546340195,24009746257,7210541490,20716225895,23072219963,15257871308,321129969182
4,1954,153315563451,16308747029,2037374129,34903529762,263839496,5308705373,25492912808,7558082163,21278479393,23797814592,16078311792,337910687090
...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,2011,711876372894,51232247600,23624757639,132833552973,11137192032,22917469985,109669382185,52052730045,98166614131,93837237783,118208323319,1792944801539
62,2012,706420870168,44579958519,23338178766,128887568646,11655890977,22357980999,107013302114,52391956399,99767726112,97055804064,119116971045,1760670227459
63,2013,722040183987,49721752068,22404030031,130944551380,11717769879,22344881459,109388604371,53702369755,100256426891,98923181463,123021130374,1799765990450
64,2014,705611747648,51321551605,22736711813,124263314517,11939156363,21877578423,102335931469,54087653912,98874388852,100532401097,115972956704,1724944564293
65,2015,722561538316,54675970819,23375961951,124566831310,12346924852,22521998699,104976597217,55417987930,100687552693,103292786749,118778641731,1776815415910

**Ejercicio:** Como podemos combinar los dos "if"? Generar una lista de nombres de columnas que no tenga las variables de demanda y a las de oferta le agregamos Super al principio.

In [ ]:
[col for col in macro.columns if not col.startswith("Demanda") and not col.startswith("Oferta")] + ["Super"+col for col in macro.columns if col.startswith("Oferta")]

['ano',
 'pbi',
 'SuperOfertaAgricultura',
 'SuperOfertaMinas',
 'SuperOfertaManufacturera',
 'SuperOfertaElectricidad',
 'SuperOfertaConstruccion',
 'SuperOfertaComercio',
 'SuperOfertaTransporte',
 'SuperOfertaFinaciera',
 'SuperOfertaSociales',
 'SuperOfertaImpuestos']

**Ejercicio.** Por un error en el formato CSV, todos los nombres de columnas en el siguiente dataframe excepto "ano" tienen un espacio adelante. Generar un DataFrame macroClean con los nombres arreglados.
1. Realizarlo utilizando la función str.strip
2. Realizarlo utilizando c[1:] para eliminar el primer caracter en los casos que corresponda

In [90]:
macroEspacio = pd.read_csv("OfertaYDemandaEspacio.csv")
macroEspacio.head()

,ano,pbi,OfertaAgricultura,OfertaMinas,OfertaManufacturera,OfertaElectricidad,OfertaConstruccion,OfertaComercio,OfertaTransporte,OfertaFinaciera,...,DemandaConsumoHogares,DemandaConsumoGobiertano,DemandaConstrucciones,DemandaMaterialNacional,DemandaMaterialImportada,DemandaMaquinariaNacional,DemandaMaquinariaImportaciones,DemandaExportaciones,DemandaImportaciones,DemandaGib
0,1950,142098481044,13696637358,1452011417,32304751942,198218385,5918090281,25281650565,7262970408,19550757718,...,104655579712,21706316451,20353627362,668586865,584400198,3119383475,863112352,10729585056,14039465296,142098481044
1,1951,147436076837,14629457210,1686941522,33149279696,212725994,6060937395,26260862055,7534071597,19902737804,...,110537717447,21767097618,21739314091,842740200,2532757698,3562534310,1292775007,8455493993,15744444593,147436076837
2,1952,140491256038,12545616104,1794762161,32522906863,227896262,5571363747,24417324287,7017131008,20598804008,...,105108053681,21455589059,19685428171,1119084065,1484421674,3440750327,1088415946,6224082425,11637586183,140491256038
3,1953,147324304004,16402296333,1925706862,32341045582,242404261,5546340195,24009746257,7210541490,20716225895,...,106402901621,20742065172,20237375978,1207890913,1459988875,3621895632,886926720,9619869463,9626750804,147324304004
4,1954,153315563451,16308747029,2037374129,34903529762,263839496,5308705373,25492912808,7558082163,21278479393,...,114392396415,21238933697,19372130307,1173451578,805900196,4121320340,783079947,10201623290,12506287869,153315563451

In [91]:
macroEspacio.columns

Index(['ano', ' pbi', ' OfertaAgricultura', ' OfertaMinas',
       ' OfertaManufacturera', ' OfertaElectricidad', ' OfertaConstruccion',
       ' OfertaComercio', ' OfertaTransporte', ' OfertaFinaciera',
       ' OfertaSociales', ' OfertaImpuestos', ' DemandaConsumoHogares',
       ' DemandaConsumoGobiertano', ' DemandaConstrucciones',
       ' DemandaMaterialNacional', ' DemandaMaterialImportada',
       ' DemandaMaquinariaNacional', ' DemandaMaquinariaImportaciones',
       ' DemandaExportaciones', ' DemandaImportaciones', ' DemandaGib'],
      dtype='str')

In [92]:
macroClean= macroEspacio.copy()
macroClean.columns = macroClean.columns.str.strip()
macroClean.columns

Index(['ano', 'pbi', 'OfertaAgricultura', 'OfertaMinas', 'OfertaManufacturera',
       'OfertaElectricidad', 'OfertaConstruccion', 'OfertaComercio',
       'OfertaTransporte', 'OfertaFinaciera', 'OfertaSociales',
       'OfertaImpuestos', 'DemandaConsumoHogares', 'DemandaConsumoGobiertano',
       'DemandaConstrucciones', 'DemandaMaterialNacional',
       'DemandaMaterialImportada', 'DemandaMaquinariaNacional',
       'DemandaMaquinariaImportaciones', 'DemandaExportaciones',
       'DemandaImportaciones', 'DemandaGib'],
      dtype='str')

In [95]:
macroClean2= macroEspacio.copy()
macroClean2.columns = [col[1:] if col.startswith(" ") else col for col in macroClean2.columns]
macroClean2.columns

Index(['ano', 'pbi', 'OfertaAgricultura', 'OfertaMinas', 'OfertaManufacturera',
       'OfertaElectricidad', 'OfertaConstruccion', 'OfertaComercio',
       'OfertaTransporte', 'OfertaFinaciera', 'OfertaSociales',
       'OfertaImpuestos', 'DemandaConsumoHogares', 'DemandaConsumoGobiertano',
       'DemandaConstrucciones', 'DemandaMaterialNacional',
       'DemandaMaterialImportada', 'DemandaMaquinariaNacional',
       'DemandaMaquinariaImportaciones', 'DemandaExportaciones',
       'DemandaImportaciones', 'DemandaGib'],
      dtype='str')